# Generated by Django 3.1.1 on 2020-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
