# Generated by Django 3.1.1 on 2020-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20200918_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='video',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
