# Generated by Django 3.1.1 on 2020-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('C', 'Country'), ('P', 'Politics'), ('I', 'Idea'), ('E', 'Economy'), ('H', 'Health')], max_length=100),
        ),
    ]
