# Generated by Django 3.1.1 on 2020-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200907_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('C', 'Country'), ('P', 'Politics'), ('I', 'Idea'), ('E', 'Economy'), ('H', 'Health')], max_length=200, null=True),
        ),
    ]
