# Generated by Django 3.1.1 on 2020-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200907_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('C', 'Country'), ('P', 'Politics'), ('E', 'Economy'), ('H', 'Health'), ('T', 'Tourism'), ('Ed', 'Education'), ('S', 'Sports')], max_length=200, null=True),
        ),
    ]
